name: Main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Kubernetes
        run: minikube start
      - name: Initialize
        run: terraform -chdir=test init
      - name: Validate
        run: terraform -chdir=test validate
      - name: Lint
        run: terraform fmt -recursive -check
      - name: Apply
        run: terraform -chdir=test apply -auto-approve
      - name: Apply Idempotency Check
        run: terraform -chdir=test plan -detailed-exitcode
      - name: Destroy
        run: terraform -chdir=test destroy -auto-approve
      - name: Destroy Idempotency Check
        run: terraform -chdir=test plan -detailed-exitcode -destroy
